stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: maven:3-adoptopenjdk-11
          shellScript: mvn package -DskipTests
  - name: Build Docker with DIND
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: docker.dev.folio.org/mod-circulation-storage:circstore-273
          pushRemote: true
          registry: docker.dev.folio.org
  - name: Deploy
    steps:
      - applyAppConfig:
          catalogTemplate: p-jqjbc:vega-helmcharts-mod-circulation-storage
          version: 0.1.32
          answers:
            image.repository: docker.dev.folio.org/mod-circulation-storage
            image.tag: circstore-273
          targetNamespace: vega
          name: mod-circulation-storage
timeout: 60
notification: {}
