version: "3.5"
services:
  service:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=folio
      - DB_PASSWORD=folio
      - DB_DATABASE=folio
    ports:
      - "8081:8081"
networks:
  default:
    name: folio_network
    external: true

